//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Reader_Book = new HashSet<Reader_Book>();
            this.Borrwed_Book = new HashSet<Borrwed_Book>();
        }
    
        public int book_id { get; set; }
        public string title { get; set; }
        public string edition { get; set; }
        public Nullable<int> pages { get; set; }
        public Nullable<int> NoOfCopies { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> auther_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> shelf_id { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public string book_image { get; set; }
        public Nullable<int> reservedbooks { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Shelf Shelf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reader_Book> Reader_Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrwed_Book> Borrwed_Book { get; set; }
    }
}
