//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrarySystemEntities : DbContext
    {
        public LibrarySystemEntities()
            : base("name=LibrarySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Borrwed_Book> Borrwed_Book { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Reader_Book> Reader_Book { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users1 { get; set; }
        public virtual DbSet<User_Permsions> User_Permsions { get; set; }
        public virtual DbSet<User_Status> User_Status { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
    
        public virtual ObjectResult<string> Search_Member_By_Name(string s)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Search_Member_By_Name", sParameter);
        }
    
        public virtual ObjectResult<ReadingBooks_Result1> ReadingBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReadingBooks_Result1>("ReadingBooks");
        }
    }
}
