//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrarySystemEntities : DbContext
    {
        public LibrarySystemEntities()
            : base("name=LibrarySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<Reader_Book> Reader_Book { get; set; }
        public virtual DbSet<Shelf> Shelf { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Borrwed_Book> Borrwed_Book { get; set; }
    
        public virtual ObjectResult<ReadingBooks_Result2> ReadingBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReadingBooks_Result2>("ReadingBooks");
        }
    
        public virtual ObjectResult<string> Search_Member_By_Name(string s)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Search_Member_By_Name", sParameter);
        }
    
        public virtual ObjectResult<string> Search_Member_By_email(string s)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Search_Member_By_email", sParameter);
        }
    }
}
