//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Project
{
    using System;
    
    public partial class ReadingBooks_Result2
    {
        public string FullName { get; set; }
        public string title { get; set; }
        public string Name { get; set; }
        public string edition { get; set; }
        public System.DateTime issu_Date { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> status { get; set; }
        public int request_id { get; set; }
        public string request_status { get; set; }
    }
}
