//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_System_Project
{
    using System;
    
    public enum UserType : int
    {
        BasicAdmin = 0,
        Admin = 1,
        Employee = 2,
        Member = 3
    }
}
